package ch.bbw.cg.gamelogic;

public class Rule {
    private CellState ruleAppliedOnState;
    private CellState ruleOfState;

    public enum RuleType {
        ALIVE_DEAD, ALIVE_UNDEAD, ALIVE_INFECTED, ALIVE_PREGNANT, ALIVE_PROTECTED, ALIVE_IMMORTAL,
        DEAD_ALIVE, DEAD_UNDEAD, DEAD_INFECTED, DEAD_PREGNANT, DEAD_PROTECTED, DEAD_IMMORTAL,
        UNDEAD_ALIVE, UNDEAD_DEAD, UNDEAD_INFECTED, UNDEAD_PREGNANT, UNDEAD_PROTECTED, UNDEAD_IMMORTAL,
        INFECTED_ALIVE, INFECTED_DEAD, INFECTED_UNDEAD, INFECTED_PREGNANT, INFECTED_PROTECTED, INFECTED_IMMORTAL,
        PREGNANT_ALIVE, PREGNANT_DEAD, PREGNANT_UNDEAD, PREGNANT_INFECTED, PREGNANT_PROTECTED, PREGNANT_IMMORTAL,
        PROTECTED_ALIVE, PROTECTED_DEAD, PROTECTED_UNDEAD, PROTECTED_INFECTED, PROTECTED_PREGNANT, PROTECTED_IMMORTAL,
        IMMORTAL_ALIVE, IMMORTAL_DEAD, IMMORTAL_UNDEAD, IMMORTAL_INFECTED, IMMORTAL_PREGNANT, IMMORTAL_PROTECTED;
    }

    public Rule(CellState ruleAppliedOnState, CellState ruleOfState) {
        this.ruleAppliedOnState = ruleAppliedOnState;
        this.ruleOfState = ruleOfState;
    }
}
